services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  cli_chat_server:
    build:
      context: ../../
      dockerfile: ./examples/cli_chat/Dockerfile
    ports:
      - "8765:8765"
    environment:
      - BROKER=redis
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
