services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  cli-chat-server:
    build:
      context: ../../
      dockerfile: ./examples/cli_chat/Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8765:8765"
    environment:
      - BROKER=redis
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
