apiVersion: v1
kind: PersistentVolume
metadata:
  name: chat-history-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/chat-history
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-history-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 